# Generated by Django 3.2.7 on 2021-10-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allegy_product',
            table='allegy_products',
        ),
    ]
